--[[
Spriteloq metadata
Generated by SpriteLoq: Loqheart's Flash SWF to sprite sheet Corona SDK exporter (c) Loqheart 2011
version 1.4.10
target Corona SDK
extension lua
exportName scootoloo
exportPath file:///C:/websites/HTML5/Framework/TinyWings/trunk/art
sheetSize 256x256
sources 1
name; url; referencePoint; startFrame; totalFrames; frameRate; topLeft; bottomRight; sourceRect; loopParam; includeReverse; rasterize
slick; ../../../Artwork/TinyWings/Character/slick.swf; (x=0, y=0); 1; 10; 30; (x=0, y=8); (x=72, y=78); (x=-2, y=6, w=76, h=74); 1; false; false
assetShapes 0
]]

local sheet = false
local setInfo = false
local msFactor = 500  -- This should be 1000 ms. Corona BUG: The frame rate is playing back at around half speed at 30fps.

local function newSpriteSet(_sheet, _name, _startFrame, _frameCount, _frameRate, _loopParam, _xReference, _yReference, _spriteSourceWidth, _spriteSourceHeight, _unscaledSpriteX, _unscaledSpriteY, _unscaledSpriteWidth, _unscaledSpriteHeight, _frames, _shapeOnly)
    if (_shapeOnly) then
        return
    end

    local set = sprite.newSpriteSet(_sheet, _startFrame, _frameCount)
    sprite.add(set, _name, 1, _frameCount, (_frameCount / _frameRate) * msFactor, _loopParam)
    setInfo[_name] = {set = set, xReference = _xReference, yReference = _yReference, spriteSourceSize = {width = _spriteSourceWidth, height = _spriteSourceHeight}, unscaledSpriteRect = {x = _unscaledSpriteX, y = _unscaledSpriteY, width = _unscaledSpriteWidth, height = _unscaledSpriteHeight}, frames = _frames, frameRate = _frameRate, frameCount = _frameCount, fpss = _frameRate / 1000, startFrame = _startFrame}
end

local function load()
    local frameSets = {}
    local allFrames = {}

    frameSets["slick"] = {
        {
            name="slick-1",
            spriteColorRect={x=1, y=1},
            textureRect={x=0, y=74, width=75, height=73},
            spriteSourceSize={width=76, height=74},
            spriteTrimmed=true,
        },
        {
            name="slick-2",
            spriteColorRect={x=1, y=1},
            textureRect={x=0, y=74, width=75, height=73},
            spriteSourceSize={width=76, height=74},
            spriteTrimmed=true,
        },
        {
            name="slick-3",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=0, width=76, height=74},
            spriteSourceSize={width=76, height=74},
            spriteTrimmed=false,
        },
        {
            name="slick-4",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=0, width=76, height=74},
            spriteSourceSize={width=76, height=74},
            spriteTrimmed=false,
        },
        {
            name="slick-5",
            spriteColorRect={x=1, y=1},
            textureRect={x=75, y=74, width=75, height=73},
            spriteSourceSize={width=76, height=74},
            spriteTrimmed=true,
        },
        {
            name="slick-6",
            spriteColorRect={x=1, y=1},
            textureRect={x=75, y=74, width=75, height=73},
            spriteSourceSize={width=76, height=74},
            spriteTrimmed=true,
        },
        {
            name="slick-7",
            spriteColorRect={x=1, y=0},
            textureRect={x=76, y=0, width=75, height=74},
            spriteSourceSize={width=76, height=74},
            spriteTrimmed=true,
        },
        {
            name="slick-8",
            spriteColorRect={x=1, y=0},
            textureRect={x=76, y=0, width=75, height=74},
            spriteSourceSize={width=76, height=74},
            spriteTrimmed=true,
        },
        {
            name="slick-9",
            spriteColorRect={x=1, y=1},
            textureRect={x=151, y=0, width=75, height=73},
            spriteSourceSize={width=76, height=74},
            spriteTrimmed=true,
        },
        {
            name="slick-10",
            spriteColorRect={x=1, y=1},
            textureRect={x=151, y=0, width=75, height=73},
            spriteSourceSize={width=76, height=74},
            spriteTrimmed=true,
        }
    }
    allFrames = table.copy(allFrames, frameSets["slick"])


    sheet = sprite.newSpriteSheetFromData("scootoloo.png", {frames = allFrames })

    -- setInfo table contains info about sprites: { (spriteName = {set: set, xReference: xReference, yReference: yReference, spriteSourceSize = {width: width, height: height}})+ }
    setInfo = {}
    newSpriteSet(sheet, "slick", 1, 10, 30, 1, 0 - (76/2 + -2), 0 - (74/2 + 6), 76, 74, 1, 1, 75, 73, frameSets["slick"], false)

    local shapes = {}
    shapes["slick"] = {

    }

    return { sheet = sheet, setInfo = setInfo, shapes = shapes }
end

local function destroy()
    sheet:dispose()
    sheet = nil
    setInfo = nil
end

return { load = load, destroy = destroy }
